export const ACTIVITY_TYPES = {
  DEAL_CREATED: 'DEAL_CREATED',
  DEAL_STAGE_CHANGED: 'DEAL_STAGE_CHANGED',
  TASK_CREATED: 'TASK_CREATED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  QUOTATION_CREATED: 'QUOTATION_CREATED',
  QUOTATION_SENT: 'QUOTATION_SENT',
  INVOICE_CREATED: 'INVOICE_CREATED',
  INVOICE_SENT: 'INVOICE_SENT',
  INVOICE_PAYMENT_RECORDED: 'INVOICE_PAYMENT_RECORDED',
  INVOICE_PARTIALLY_PAID: 'INVOICE_PARTIALLY_PAID',
  INVOICE_PAID: 'INVOICE_PAID',
  INVOICE_OVERDUE: 'INVOICE_OVERDUE',
  INVOICE_CANCELLED: 'INVOICE_CANCELLED',
  NOTE_CREATED: 'NOTE_CREATED',
  CONVERSATION_ASSIGNED: 'CONVERSATION_ASSIGNED',
  CONVERSATION_NOTE_CREATED: 'CONVERSATION_NOTE_CREATED',
  DEAL_CREATED_FROM_CHAT: 'DEAL_CREATED_FROM_CHAT',
} as const;

export type ActivityType = (typeof ACTIVITY_TYPES)[keyof typeof ACTIVITY_TYPES];
