export const LEAD_SOURCES = {
  CODE2CREST_GET_QUOTE: 'CODE2CREST_GET_QUOTE',
  CODE2CREST_CONTACT: 'CODE2CREST_CONTACT',
  WHATSAPP: 'WHATSAPP',
  LINKEDIN: 'LINKEDIN',
  GOOGLE_BUSINESS: 'GOOGLE_BUSINESS',
  REFERRAL: 'REFERRAL',
  META_ADS: 'META_ADS',
  MANUAL: 'MANUAL',
} as const;

export type LeadSource = (typeof LEAD_SOURCES)[keyof typeof LEAD_SOURCES];
