import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { prisma } from '../config/database.js';
import { getDealWhere } from '../middleware/permissions.js';
import type { AuthPayload } from '../types/index.js';
import {
  CODE2CREST_CLIENT_ONBOARDING_SYSTEM_KEY,
  groupOnboardingSubmissionValues,
} from './clientOnboarding.service.js';

const pageWidth = 595.28;
const pageHeight = 841.89;
const margin = 42;
const primary = rgb(0, 0.278, 0.255);
const text = rgb(0.063, 0.125, 0.114);
const muted = rgb(0.42, 0.478, 0.459);
const border = rgb(0.867, 0.847, 0.804);

function displayName(contact?: { firstName?: string | null; lastName?: string | null; companyName?: string | null; contactPersonName?: string | null } | null) {
  return contact?.companyName || contact?.contactPersonName || [contact?.firstName, contact?.lastName].filter(Boolean).join(' ').trim() || 'Client';
}

function wrapText(value: string, maxChars: number) {
  const words = value.split(/\s+/);
  const lines: string[] = [];
  let current = '';
  words.forEach((word) => {
    if ((current + ' ' + word).trim().length > maxChars) {
      if (current) lines.push(current);
      current = word;
    } else {
      current = `${current} ${word}`.trim();
    }
  });
  if (current) lines.push(current);
  return lines.length ? lines : [''];
}

export async function generateClientOnboardingPdf(auth: AuthPayload, dealId: string) {
  const deal = await prisma.deal.findFirst({
    where: { id: dealId, ...getDealWhere(auth) },
    include: {
      contact: true,
      company: true,
      formSubmissions: {
        where: { form: { systemKey: CODE2CREST_CLIENT_ONBOARDING_SYSTEM_KEY } },
        include: {
          values: { include: { field: true }, orderBy: { createdAt: 'asc' } },
        },
        orderBy: { submittedAt: 'desc' },
        take: 1,
      },
    },
  });
  if (!deal) return null;
  const submission = deal.formSubmissions[0];
  if (!submission) return null;

  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  let page = pdf.addPage([pageWidth, pageHeight]);
  let y = pageHeight - margin;

  function newPage() {
    page = pdf.addPage([pageWidth, pageHeight]);
    y = pageHeight - margin;
  }

  function drawFooter() {
    page.drawLine({ start: { x: margin, y: 34 }, end: { x: pageWidth - margin, y: 34 }, thickness: 0.7, color: border });
    page.drawText('Generated by LeadFlow', { x: margin, y: 18, size: 9, font, color: muted });
    page.drawText('Code2Crest Technologies', { x: pageWidth - margin - 118, y: 18, size: 9, font, color: muted });
  }

  function ensure(space: number) {
    if (y - space < 55) {
      drawFooter();
      newPage();
    }
  }

  function drawLine(label: string, value: string) {
    ensure(22);
    page.drawText(label, { x: margin, y, size: 9, font: bold, color: muted });
    page.drawText(value || '-', { x: margin + 128, y, size: 10, font, color: text });
    y -= 18;
  }

  page.drawText('CLIENT ONBOARDING', { x: margin, y, size: 24, font: bold, color: primary });
  page.drawText(deal.company.name || 'Code2Crest Technologies', { x: pageWidth - margin - 190, y: y + 4, size: 12, font: bold, color: text });
  y -= 34;
  page.drawLine({ start: { x: margin, y }, end: { x: pageWidth - margin, y }, thickness: 1, color: border });
  y -= 24;

  drawLine('Client', displayName(deal.contact));
  drawLine('Email', deal.contact.email || '-');
  drawLine('Phone', `${deal.contact.phoneCountryCode || ''} ${deal.contact.phoneNumber || ''}`.trim());
  drawLine('Deal', deal.title);
  drawLine('Status', deal.onboardingStatus);
  drawLine('Submitted', submission.submittedAt.toISOString());
  y -= 8;

  groupOnboardingSubmissionValues(submission).forEach((group) => {
    ensure(42);
    page.drawText(group.section, { x: margin, y, size: 14, font: bold, color: primary });
    y -= 16;
    page.drawLine({ start: { x: margin, y }, end: { x: pageWidth - margin, y }, thickness: 0.7, color: border });
    y -= 14;

    group.answers.forEach((answer) => {
      const labelLines = wrapText(answer.label, 24);
      const valueLines = wrapText(answer.displayValue || '-', 70);
      const rowHeight = Math.max(labelLines.length, valueLines.length) * 13 + 8;
      ensure(rowHeight + 4);
      page.drawText(labelLines[0] || answer.label, { x: margin, y, size: 9, font: bold, color: muted });
      valueLines.forEach((line, index) => {
        page.drawText(line, { x: margin + 150, y: y - index * 13, size: 10, font, color: text });
      });
      y -= rowHeight;
    });
    y -= 8;
  });

  drawFooter();
  pdf.setTitle(`${deal.title} - Client Onboarding`);
  pdf.setAuthor(deal.company.name || 'Code2Crest Technologies');
  pdf.setCreator('LeadFlow CRM');
  pdf.setProducer('LeadFlow CRM');
  return Buffer.from(await pdf.save());
}
